-- Additive Telegram notifications for P2P order creation and status changes.
-- This queue is private; delivery is performed by a service-role Edge Function.

create table if not exists public.aura_telegram_notification_queue (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text not null,
  title text not null,
  message text not null,
  status text not null default 'pending'
    check (status in ('pending','processing','sent','failed')),
  attempt_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz
);

create index if not exists aura_telegram_notification_queue_pending_idx
  on public.aura_telegram_notification_queue(status, id)
  where status in ('pending','processing');

alter table public.aura_telegram_notification_queue enable row level security;
revoke all on public.aura_telegram_notification_queue from public, anon, authenticated;
grant select, insert, update, delete on public.aura_telegram_notification_queue to service_role;
grant usage, select on sequence public.aura_telegram_notification_queue_id_seq to service_role;

create or replace function public.queue_p2p_telegram_notifications()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_recipient record;
  v_trade text := left(new.id::text, 8);
  v_amount text := coalesce(new.crypto_amount::text, '0');
  v_status text := upper(replace(coalesce(new.status, 'updated'), '_', ' '));
begin
  if tg_op = 'INSERT' then
    for v_recipient in
      select p.id, p.telegram_user_id, p.telegram_bot_alerts,
             case when p.id = new.seller_id then 'New P2P trade request' else 'P2P trade created' end as notification_title
      from public.profiles p
      where p.id in (new.buyer_id, new.seller_id)
        and p.telegram_user_id ~ '^[0-9]{1,20}$'
        and coalesce(p.telegram_bot_alerts, true)
    loop
      insert into public.aura_telegram_notification_queue(user_id, event_type, title, message)
      values (
        v_recipient.id,
        'p2p_order_created',
        v_recipient.notification_title,
        format('Trade #%s was created for %s %s. Open AURA to review the trade and its current details.', v_trade, v_amount, coalesce(new.fiat_currency, 'USDT'))
      );
    end loop;
  elsif new.status is distinct from old.status then
    for v_recipient in
      select p.id
      from public.profiles p
      where p.id in (new.buyer_id, new.seller_id)
        and p.telegram_user_id ~ '^[0-9]{1,20}$'
        and coalesce(p.telegram_bot_alerts, true)
    loop
      insert into public.aura_telegram_notification_queue(user_id, event_type, title, message)
      values (
        v_recipient.id,
        'p2p_order_status',
        'P2P trade status updated',
        format('Trade #%s status is now %s. Open AURA to review the latest trade details.', v_trade, v_status)
      );
    end loop;
  end if;
  return new;
end;
$function$;

drop trigger if exists p2p_orders_queue_telegram_notifications on public.p2p_orders;
create trigger p2p_orders_queue_telegram_notifications
after insert or update of status on public.p2p_orders
for each row execute function public.queue_p2p_telegram_notifications();

create or replace function public.claim_aura_telegram_notifications(p_limit integer default 50)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_result jsonb;
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED';
  end if;

  with candidates as (
    select q.id
    from public.aura_telegram_notification_queue q
    where q.status = 'pending'
       or (q.status = 'processing' and q.updated_at < now() - interval '5 minutes')
    order by q.id
    for update skip locked
    limit greatest(1, least(coalesce(p_limit, 50), 100))
  ),
  claimed as (
    update public.aura_telegram_notification_queue q
    set status = 'processing',
        attempt_count = q.attempt_count + 1,
        updated_at = now()
    from candidates c
    where q.id = c.id
    returning q.id, q.user_id, q.title, q.message, q.attempt_count
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id', c.id,
    'user_id', c.user_id,
    'title', c.title,
    'message', c.message,
    'attempt_count', c.attempt_count,
    'telegram_user_id', p.telegram_user_id
  ) order by c.id), '[]'::jsonb)
  into v_result
  from claimed c
  join public.profiles p on p.id = c.user_id;

  return v_result;
end;
$function$;

create or replace function public.complete_aura_telegram_notification(
  p_id bigint,
  p_success boolean,
  p_error text default null
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  if coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'SERVICE_ROLE_REQUIRED';
  end if;

  update public.aura_telegram_notification_queue
  set status = case
        when p_success then 'sent'
        when attempt_count >= 5 then 'failed'
        else 'pending'
      end,
      sent_at = case when p_success then now() else sent_at end,
      last_error = case when p_success then null else left(coalesce(p_error, 'TELEGRAM_DELIVERY_FAILED'), 500) end,
      updated_at = now()
  where id = p_id and status = 'processing';
end;
$function$;

revoke all on function public.queue_p2p_telegram_notifications() from public, anon, authenticated;
revoke all on function public.claim_aura_telegram_notifications(integer) from public, anon, authenticated;
revoke all on function public.complete_aura_telegram_notification(bigint, boolean, text) from public, anon, authenticated;
grant execute on function public.claim_aura_telegram_notifications(integer) to service_role;
grant execute on function public.complete_aura_telegram_notification(bigint, boolean, text) to service_role;

do $$
begin
  if not exists (select 1 from cron.job where jobname = 'aura-telegram-p2p-notifications') then
    perform cron.schedule(
      'aura-telegram-p2p-notifications',
      '* * * * *',
      $cron$
        select net.http_post(
          url := (select decrypted_secret from vault.decrypted_secrets where name='aura_project_url') || '/functions/v1/telegram-p2p-notifications',
          headers := jsonb_build_object(
            'Content-Type','application/json',
            'apikey',(select decrypted_secret from vault.decrypted_secrets where name='aura_publishable_key'),
            'x-aura-worker-secret',(select decrypted_secret from vault.decrypted_secrets where name='aura_worker_secret')
          ),
          body := jsonb_build_object('source','supabase-cron')
        ) as request_id;
      $cron$
    );
  end if;
end
$$;
